In [2]:
import pandas as pd

df = pd.read_csv("data/udemy_lang.csv")

In [4]:
df.shape

(83104, 13)

In [5]:
df = df[["title", "url", "duration", "language"]]

In [6]:
df = df.dropna(subset=["title", "url"])

In [7]:
df["title"] = df["title"].str.lower().str.strip()
df["language"] = df["language"].fillna("unknown").str.lower()

In [8]:
df.isnull().sum()
df.shape

(83104, 4)

In [9]:
domain_keywords = {
    "AI": [
        "artificial intelligence",
        "machine learning",
        "deep learning",
        "neural network",
        "computer vision",
        "nlp",
        " ai ",
        "ai-",
        " ai"
    ],
    "Web": ["web development", "html", "css", "javascript", "react", "angular"],
    "Data": ["data science", "data analysis", "pandas", "numpy", "sql"],
    "Cloud": ["aws", "azure", "google cloud", "cloud computing", "devops"]
}

In [10]:
def assign_domain(title):
    title = " " + title + " "   # avoids ai inside agile
    for domain, keywords in domain_keywords.items():
        for kw in keywords:
            if kw in title:
                return domain
    return "Other"

In [11]:
df["domain"] = df["title"].apply(assign_domain)

In [12]:
df["domain"].value_counts()

domain
Other    77326
Web       1892
Cloud     1394
Data      1365
AI        1127
Name: count, dtype: int64

In [13]:
df.head()

,title,url,duration,language,domain
0,the complete python bootcamp from zero to hero...,/course/complete-python-bootcamp/,22 total hours,en,Other
1,the complete 2023 web development bootcamp,/course/the-complete-web-development-bootcamp/,65.5 total hours,en,Web
2,the web developer bootcamp 2023,/course/the-web-developer-bootcamp/,64 total hours,en,Other
3,angular - the complete guide (2023 edition),/course/the-complete-guide-to-angular-2/,34.5 total hours,en,Web
4,100 days of code: the complete python pro boot...,/course/100-days-of-code/,64 total hours,en,Other

In [14]:
df.head(10)

,title,url,duration,language,domain
0,the complete python bootcamp from zero to hero...,/course/complete-python-bootcamp/,22 total hours,en,Other
1,the complete 2023 web development bootcamp,/course/the-complete-web-development-bootcamp/,65.5 total hours,en,Web
2,the web developer bootcamp 2023,/course/the-web-developer-bootcamp/,64 total hours,en,Other
3,angular - the complete guide (2023 edition),/course/the-complete-guide-to-angular-2/,34.5 total hours,en,Web
4,100 days of code: the complete python pro boot...,/course/100-days-of-code/,64 total hours,en,Other
5,java programming masterclass updated to java 17,/course/java-the-complete-java-developer-course/,103.5 total hours,en,Other
6,"react - the complete guide (incl hooks, react ...",/course/react-the-complete-guide-incl-redux/,48.5 total hours,en,Web
7,the complete javascript course 2023: from zero...,/course/the-complete-javascript-course/,69 total hours,en,Web
8,machine learning a-z™: python & r in data scie...,/course/machinelearning/,42.5 total hours,en,AI
9,python for data science and machine learning b...,/course/python-for-data-science-and-machine-le...,25 total hours,en,AI

In [15]:
domain_keywords = {
    "AI": [
        "artificial intelligence",
        "machine learning",
        "deep learning",
        "neural network",
        "computer vision",
        "natural language processing",
        " ai ",
        "ai-"
    ],
    "Web": [
        "web development",
        "web developer",
        "frontend",
        "backend",
        "full stack",
        "html",
        "css",
        "javascript",
        "react",
        "angular"
    ],
    "Data": [
        "data science",
        "data scientist",
        "data analysis",
        "data analyst",
        "machine learning",
        "pandas",
        "numpy",
        "sql"
    ],
    "Cloud": [
        "cloud computing",
        "aws",
        "azure",
        "google cloud",
        "devops",
        "docker",
        "kubernetes"
    ]
}

In [16]:
df["domain"] = df["title"].apply(assign_domain)
df["domain"].value_counts()

domain
Other    77264
Web       2010
Cloud     1566
Data      1404
AI         860
Name: count, dtype: int64

In [17]:
df[df["domain"] == "AI"][["title", "domain"]].head(10)

                                                 title domain
8    machine learning a-z™: python & r in data scie...     AI
9    python for data science and machine learning b...     AI
39   deep learning a-z™: hands-on artificial neural...     AI
63   machine learning, data science and deep learni...     AI
87   artificial intelligence a-z™: learn how to bui...     AI
114  complete guide to tensorflow for deep learning...     AI
123  data science and machine learning bootcamp with r     AI
135  complete machine learning & data science bootc...     AI
151      nlp - natural language processing with python     AI
158  introduction to machine learning for data science     AI